openapi: 3.0.0
info:
  title: Azure ML Image Analysis API
  version: 1.0.0
  description: API für die Bildanalyse unter Verwendung eines YOLO-Modells und Azure OCR-Diensten
paths:
  /analyse:
    post:
      summary: Bildanalyse durchführen
      description: Sendet ein Bild an den Endpunkt und erhält Bounding Boxes und Textanalyse zurück.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
                  description: Das Bild als Datei
                ext:
                  type: string
                  description: Die Dateierweiterung des Bildes (z. B. "jpeg", "png")
      responses:
        '200':
          description: Erfolgreiche Antwort mit den Analyseergebnissen
          content:
            application/json:
              schema:
                type: object
                properties:
                  predictions:
                    type: array
                    items:
                      type: object
                      properties:
                        class:
                          type: string
                          description: Die Vorhersageklasse (z. B. "Person", "Auto")
                        box:
                          type: object
                          properties:
                            x1:
                              type: number
                              description: X-Koordinate der linken oberen Ecke der Bounding Box
                            y1:
                              type: number
                              description: Y-Koordinate der linken oberen Ecke der Bounding Box
                            x2:
                              type: number
                              description: X-Koordinate der rechten unteren Ecke der Bounding Box
                            y2:
                              type: number
                              description: Y-Koordinate der rechten unteren Ecke der Bounding Box
                        text:
                          type: array
                          items:
                            type: string
                          description: Erkanntes Text aus OCR
        '400':
          description: Fehlende oder ungültige Eingabe
        '500':
          description: Interner Serverfehler
