users: 2
spawn_rate: 1
run_time: 1m
api_key: "EOLqlbiHInFPB2qj5s7L0mqZHWvxOnoASrgub3odRS3tpaTuhoN0JQQJ99BCAAAAAAAAAAAAINFRAZML3lyt"
test_images:
  - "images/small.png"
  - "images/medium.png"
  - "images/large.png"
failure_limit: 0.05
host: "https://endpunkt-mjyxx.germanywestcentral.inference.ml.azure.com"
wait_time:
  min: 0.1
  max: 0.5
